#!/bin/bash
set -e

DOCKER_URL=$1
DOCKER_USERNAME=$2
DOCKER_PASSWORD=$3
DOCKER_REPO=$4
REPO=$5
BUILD_NUMBER=$6
DOCKER_FILE=$7

docker login ${DOCKER_URL} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
docker build -f ${DOCKER_FILE} -t ${REPO}:${BUILD_NUMBER} .
docker tag ${REPO}:${BUILD_NUMBER} ${DOCKER_URL}/${DOCKER_REPO}/${REPO}:${BUILD_NUMBER}
docker push ${DOCKER_URL}/${DOCKER_REPO}/${REPO}:${BUILD_NUMBER}