apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    app: {{ .Values.serviceName }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
spec:
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: 8081
      protocol: TCP
    - name: https
      port: {{ .Values.httpsPort }}
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer
